[project]
name = "databasefun"
version = "0.1.0"
description = "Add a short description here"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"
jupyter = ">=1.0.0,<1.1"
pytest = ">=8.1.1,<8.2"
pandas = ">=2.2.1,<2.3"
